### ISSUE TITLE
Raspberry Pi 3 

### ISSUE THREAD

**Issue by princesslyons** [joseph-jja/pi-hotspot#1]
Does this project work for the Raspberry Pi 3?
I'm trying to turn my Raspberry Pi into a repeater using only wireless connections. I don't have access to an ethernet port. Essentially, I'd like my pi to broadcast it's own network while being connected to another network or simply "forwarding" that connection to its broadcasting network. Does this project do that?

**Comment by joseph-jja** [comment]
So this code is not raspberry pi specific, so should work fine on the pi 3 under raspian or ubuntu or another unix.  Not sure about noobs, never used it.  

It could be modified to be used as a repeater, but I use it more as a hot spot that connects to another hot spot. Basically it would broadcast SSID1 and connect to SSID2, similar to how some of the netgear range extenders work, but you have to specify the SSIDs

**Comment by joseph-jja** [comment]
Not an issue
